[package]
name = "imgui-vulkano-renderer"
version = "0.1.0"
authors = ["Sam Blazes"]
edition = "2018"

repository = "https://github.com/Tenebryo/imgui-vulkano-renderer"
readme = "README.md"
license-file = "LICENSE"
description = "A renderer for imgui-rs using Vulkano"
categories = ["gui", "rendering"]
keyword = ["vulkano", "imgui", "graphics", "gui", "rendering"]

[dependencies]
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
imgui = { version = "0.4.0" }

[dev-dependencies]
clipboard = "0.5.0"
imgui-winit-support = "0.4.0"
vulkano-win = "0.19.0"
winit = "0.22.2"
image = "0.23.8"