[package]
name = "imgui-vulkano-renderer"
version = "0.7.3"
authors = ["Sam Blazes"]
edition = "2018"

repository = "https://github.com/Tenebryo/imgui-vulkano-renderer"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
description = "A renderer for imgui-rs using Vulkano"
categories = ["gui", "rendering"]
keywords = ["vulkano", "imgui", "graphics", "gui", "rendering"]

[dependencies]
vulkano = "0.24.0"
vulkano-shaders = "0.24.0"
imgui = "0.7.0"

[dev-dependencies]
clipboard = "0.5.0"
imgui-winit-support = {version = "0.7.1", default-features = false, features = ["winit-25"]}
vulkano-win = "0.24.0"
# winit 0.25.0 is not supported on crates.io
winit = "0.25.0" 
image = "0.23.8"
